-- FIX FOR CONTACTS TABLE SCHEMA MISMATCH
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS research_data JSONB;

-- ENSURE LEADS IS ALSO IN SYNC
ALTER TABLE leads ADD COLUMN IF NOT EXISTS research_data JSONB;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS discovery_lead_id UUID;
