
import { db } from "@/lib/db";
import { products } from "@/lib/db/schema";
import { eq } from "drizzle-orm";

const SEED_DATA = [
    {
        sourceId: 2,
        name: "Menú Digital - Plan Emprendedor",
        price: 250,
        description: "El Plan Emprendedor es la solución perfecta para restaurantes con menús fijos o ejecutivos que buscan digitalizar su carta sin complicaciones. Este servicio incluye:<br><br>**Menú digital completo en 1 página optimizada:** Diseñado específicamente para mostrar tu menú de forma clara y atractiva, facilitando la navegación de tus clientes.<br>**Código QR dinámico:** Imprime una sola vez y funciona para siempre. Tus clientes escanean y acceden instantáneamente a tu menú actualizado.<br>**Actualizaciones ilimitadas desde tu celular:** Cambia precios, platos o descripciones en segundos, sin necesidad de conocimientos técnicos ni diseñadores.<br>**1 año de dominio + hosting incluidos:** Tu propio dominio profesional (www.turestaurante.com) con alojamiento seguro durante el primer año.<br>**Todo queda a TU nombre:** Propiedad 100% tuya del dominio, contenido y archivos. Sin dependencias ni ataduras.<br>**Posicionamiento en Google:** Tu menú aparece en búsquedas locales cuando potenciales clientes buscan 'restaurante cerca de mí' o 'almuerzos en [tu ciudad]'.<br><br>Este plan está diseñado pensando en restaurantes que ofrecen menú del día, carta ejecutiva o menús que cambian con poca frecuencia. Ideal para comenzar tu presencia digital profesional.",
        benefits: "**Ahorro de Tiempo:** Deja de perder horas diseñando menús en Canva o Word cada semana. Actualiza en 3 clics desde tu celular.<br>**Presencia Profesional:** Un menú digital moderno que genera confianza y atrae más clientes que un PDF o una foto borrosa en WhatsApp.<br>**Visibilidad en Google:** Aparece cuando clientes nuevos buscan dónde comer en tu zona. El 72% de los clientes buscan el menú online antes de decidir.<br>**Sin Comisiones:** A diferencia de apps de delivery que cobran 20-30% por pedido, esto es tuyo 100%. Cero comisiones por pedido.<br>**Actualizaciones Instantáneas:** ¿Cambió el precio del almuerzo? ¿Se acabó un plato? Actualiza en segundos y tus clientes lo ven de inmediato.<br>**Código QR Profesional:** Imprime una sola vez, funciona siempre. Colócalo en tus mesas, ventanas o tarjetas de presentación.<br>**Pedidos Directos por WhatsApp:** Integración nativa que envía a tus clientes directo a tu WhatsApp Business para hacer pedidos.<br>**Dominio Propio:** www.turestaurante.com es mucho más profesional que un enlace de Facebook o Instagram.<br>**Propiedad Total:** Todo el contenido, diseño y archivos quedan a tu nombre. No dependes de nosotros después de la entrega.<br>**Inversión Única:** Pago único de $250, sin mensualidades ocultas ni costos sorpresa.<br>**Compatible con Todos los Dispositivos:** Tu menú se ve perfecto en celulares, tablets y computadoras.<br>**Soporte Incluido:** Te ayudamos con dudas y cambios durante el primer mes sin costo adicional.",
        category: "Digitalización y Tecnología para Restaurantes",
        subCategory: "Menú Digital / Plan Básico",
        tags: "menú digital, restaurantes, QR, digitalización, Ecuador, menú ejecutivo, carta digital, sin comisiones",
        paymentForm: "Pago único",
        videoUrl: "https://www.youtube.com/watch?v=4hot82GQezI",
        servicesIncluded: "Menú digital 1 página, Código QR dinámico, Actualizaciones ilimitadas, Dominio 1 año, Hosting 1 año, Posicionamiento Google básico, Integración WhatsApp, Soporte 1 mes"
    },
    {
        sourceId: 3,
        name: "Menú Digital - Plan Crecimiento",
        price: 500,
        description: "El Plan Crecimiento está diseñado para negocios en expansión que necesitan una presencia digital más robusta. Perfecto para cafeterías, bistrós o restaurantes con múltiples categorías de menú. Incluye:<br><br>**Tu menú digital con hasta 8 páginas organizadas:** Suficiente espacio para desayunos, almuerzos, cenas, bebidas y postres, todo organizado profesionalmente.<br>**Código QR dinámico:** Imprime una vez, actualiza siempre. Funciona en mesas, tarjetas o ventanas.<br>**Actualizaciones ilimitadas desde tu celular:** Control total desde tu smartphone. Cambia lo que necesites, cuando lo necesites.<br>**1 año de dominio + hosting incluidos:** Tu dominio profesional con alojamiento seguro.<br>**Todo queda a TU nombre:** Propiedad completa del dominio, diseño y contenido.<br>**Galería de fotos para eventos:** Muestra tus platillos especiales, eventos corporativos o celebraciones que has organizado.<br>**Posicionamiento en Google mejorado:** Mayor visibilidad en búsquedas locales con múltiples páginas optimizadas.<br><br>Este plan es ideal para negocios que están creciendo y necesitan mostrar una oferta más amplia sin perder la facilidad de actualización.",
        benefits: "**Organización Profesional:** Hasta 8 páginas te permiten separar claramente desayunos, almuerzos, bebidas, postres y promociones especiales.<br>**Galería Visual:** Muestra fotos de tus mejores platos y eventos. Las imágenes venden más que mil palabras.<br>**Mayor Posicionamiento:** Más páginas = más palabras clave = más visibilidad en Google para búsquedas como 'cafetería [tu ciudad]' o 'bistrós en [zona]'.<br>**Experiencia de Cliente Mejorada:** Navegación clara y organizada que facilita la decisión de compra.<br>**Promociones Destacadas:** Espacio dedicado para resaltar tus ofertas especiales o platos del día.<br>**Sin Límites de Actualización:** Cambia menús, precios o promociones las veces que necesites, sin costo adicional.<br>**Inversión Protegida:** Todo queda a tu nombre. Si decides cambiar de proveedor en el futuro, te llevas todo.<br>**Pedidos Directos:** Integración con WhatsApp para que tus clientes ordenen directamente, sin intermediarios.<br>**Cero Comisiones:** A diferencia de plataformas de delivery, aquí no pagas comisión por pedido.<br>**Soporte Extendido:** Asistencia técnica para resolver cualquier duda durante la implementación.<br>**Adaptable a Cualquier Dispositivo:** Tu menú se ve impecable en celulares, tablets y computadoras.<br>**ROI Rápido:** Con solo 5-7 pedidos adicionales al mes ya recuperaste tu inversión.",
        category: "Digitalización y Tecnología para Restaurantes",
        subCategory: "Menú Digital / Plan Intermedio",
        tags: "menú digital, cafeterías, bistrós, QR, restaurantes en crecimiento, carta digital, marketing digital, Ecuador",
        paymentForm: "Pago único",
        videoUrl: "https://www.youtube.com/watch?v=4hot82GQezI",
        servicesIncluded: "Menú digital 8 páginas, Código QR dinámico, Actualizaciones ilimitadas, Dominio 1 año, Hosting 1 año, Galería de fotos, Posicionamiento Google intermedio, Integración WhatsApp, Promociones destacadas"
    },
    {
        sourceId: 4,
        name: "Menú Digital - Plan Pro",
        price: 700,
        description: "El Plan Pro es la solución completa para restaurantes con cartas extensas que buscan dominancia en su mercado local. Incluye:<br><br>**Tu menú digital con hasta 20 páginas (carta completa):** Espacio suficiente para mostrar entradas, platos fuertes, bebidas, vinos, postres, menús especiales y más.<br>**Código QR dinámico:** La tecnología que imprime una vez y actualiza siempre.<br>**Actualizaciones ilimitadas desde tu celular:** Control total sin límites ni costos adicionales.<br>**2 años de dominio + hosting incluidos:** El doble de tiempo de protección para tu inversión.<br>**Todo queda a TU nombre:** Propiedad absoluta de tu activo digital.<br>**Galería de eventos + promociones destacadas:** Secciones dedicadas para mostrar tus mejores momentos y ofertas especiales.<br>**Integración con redes sociales:** Conecta tu menú digital con Facebook, Instagram y WhatsApp para una presencia digital unificada.<br>**Posicionamiento Google avanzado:** Optimización técnica para aparecer en las primeras posiciones de búsqueda local.<br><br>Este plan es para restaurantes serios que entienden que su menú digital no es un gasto, sino una inversión en su futuro.",
        benefits: "**Carta Completa Digital:** Hasta 20 páginas para mostrar TODO tu menú sin limitaciones. Entradas, platos fuertes, bebidas, postres, menús especiales.<br>**2 Años de Protección:** Dominio y hosting incluidos por 2 años completos. Ahorro significativo vs renovaciones anuales.<br>**Integración Total:** Conecta tu menú con Facebook, Instagram y WhatsApp. Una sola fuente de verdad para todos tus canales.<br>**Galería Premium:** Muestra tus mejores platos, eventos corporativos, celebraciones y ambientes del restaurante.<br>**Promociones Destacadas:** Sección especial para ofertas, combos y menús del día que capturen la atención.<br>**Posicionamiento Dominante:** Optimización SEO avanzada para aparecer cuando busquen 'mejor restaurante [tu ciudad]' o 'dónde comer [zona]'.<br>**Rotación Frecuente:** Perfecto para restaurantes que cambian su carta regularmente o tienen menús estacionales.<br>**ROI Comprobado:** Con 10-12 clientes adicionales al mes ya recuperaste tu inversión. El resto es ganancia pura.<br>**Sin Comisiones por Pedido:** Mientras apps de delivery se llevan 20-30%, tú te quedas con el 100%.<br>**Propiedad Vitalicia:** Todo el código, diseño y contenido es tuyo para siempre. Cero dependencia.<br>**Soporte Prioritario:** Atención preferencial para cambios, dudas o ajustes que necesites.<br>**Marca Profesional:** Tu dominio propio (www.turestaurante.com) proyecta seriedad y confianza.<br>**Experiencia de Cliente Premium:** Navegación fluida, diseño atractivo y carga rápida en cualquier dispositivo.",
        category: "Digitalización y Tecnología para Restaurantes",
        subCategory: "Menú Digital / Plan Avanzado",
        tags: "menú digital profesional, carta digital, restaurantes, posicionamiento Google, SEO local, marketing restaurantes, Ecuador",
        paymentForm: "Pago único",
        videoUrl: "https://www.youtube.com/watch?v=4hot82GQezI",
        servicesIncluded: "Menú digital 20 páginas, Código QR dinámico, Actualizaciones ilimitadas, Dominio 2 años, Hosting 2 años, Galería eventos + promociones, Posicionamiento Google avanzado, Integración redes sociales, Integración WhatsApp, Soporte prioritario"
    },
    {
        sourceId: 5,
        name: "Menú Digital - Plan Posicionamiento",
        price: 1000,
        description: "El Plan Posicionamiento es la solución definitiva para restaurantes que buscan ser LA REFERENCIA en su ciudad y posicionarse internacionalmente. Este plan incluye:<br><br>**Tu menú digital con hasta 40 páginas (carta completa extendida):** La solución más robusta para restaurantes con múltiples menús, especialidades regionales, carta de vinos extensa y menús corporativos.<br>**Código QR dinámico:** Tecnología de actualización continua sin necesidad de reimprimir.<br>**Blog para posicionar internacionalmente:** Artículos optimizados para SEO que posicionan tu restaurante en búsquedas internacionales y de turismo.<br>**Actualizaciones ilimitadas desde tu celular:** Control absoluto sin restricciones.<br>**2 años de dominio + hosting incluidos:** Protección extendida de tu inversión digital.<br>**Todo queda a TU nombre:** Propiedad total de tu imperio digital.<br>**Galería de eventos + promociones destacadas:** Múltiples secciones visuales para mostrar tu mejor trabajo.<br>**Integración con redes sociales:** Conexión completa con todos tus canales digitales.<br>**Posicionamiento en ChatGPT y Claude:** Tu restaurante será recomendado cuando viajeros y locales pregunten a la IA dónde comer.<br><br>Este plan es para restaurantes visionarios que entienden que el futuro del marketing es digital y que quieren capturar tanto el mercado local como el turístico internacional.",
        benefits: "**40 Páginas de Contenido:** Espacio ilimitado para menús completos, especialidades, historia del restaurante, chef, eventos corporativos, banquetes y más.<br>**Blog de Posicionamiento:** Artículos optimizados que atraen tráfico orgánico. Contenido como 'Mejores restaurantes [tu ciudad]' o 'Gastronomía típica ecuatoriana'.<br>**Posicionamiento Internacional:** Tu restaurante aparece cuando turistas buscan 'dónde comer en [tu ciudad]' desde cualquier país.<br>**Recomendaciones de IA:** ChatGPT y Claude recomendarán tu restaurante cuando usuarios pregunten por opciones gastronómicas en tu zona.<br>**Captura Mercado Turístico:** El 70% de viajeros planifica online. Estar visible significa capturar esa demanda millonaria.<br>**2 Años Sin Preocupaciones:** Dominio y hosting cubiertos por 24 meses completos.<br>**Contenido Rico:** 40 páginas te permiten contar tu historia, mostrar tu equipo, tus valores, tu proceso y crear conexión emocional.<br>**ROI Extraordinario:** Con solo 2-3 reservas corporativas o grupos turísticos al mes ya recuperaste tu inversión.<br>**Cero Dependencia de OTAs:** Mientras otros pagan 15-20% de comisión en plataformas, tú recibes reservas directas al 100%.<br>**Marca Internacional:** Tu restaurante compite con cadenas internacionales en presencia digital.<br>**Propiedad Perpetua:** Todo es tuyo para siempre. El código, el contenido, el posicionamiento.<br>**Soporte VIP:** Atención personalizada y prioritaria para cualquier necesidad.<br>**Ventaja Competitiva Brutal:** Mientras tu competencia sigue con menús PDF en Facebook, tú dominas Google y las IA.<br>**Diversificación de Ingresos:** Atrae eventos corporativos, grupos turísticos, celebraciones privadas con tu presencia premium.",
        category: "Digitalización y Tecnología para Restaurantes",
        subCategory: "Menú Digital / Plan Premium",
        tags: "posicionamiento internacional, menú digital, SEO restaurantes, marketing digital, turismo gastronómico, IA, ChatGPT, Ecuador",
        paymentForm: "Pago único",
        videoUrl: "https://www.youtube.com/watch?v=4hot82GQezI",
        servicesIncluded: "Menú digital 40 páginas, Blog SEO optimizado, Código QR dinámico, Actualizaciones ilimitadas, Dominio 2 años, Hosting 2 años, Galería eventos + promociones, Posicionamiento Google premium, Posicionamiento en IA (ChatGPT/Claude), Integración redes sociales, Integración WhatsApp, Soporte VIP"
    },
    {
        sourceId: 6,
        name: "Motor de Reservas Hotel - Plan Pro",
        price: 700,
        description: "El Plan Pro es la solución perfecta para hoteles pequeños y hostales que buscan independencia de las OTAs (Booking, Expedia, Despegar) y quieren dejar de pagar comisiones del 18% por cada reserva. Incluye:<br><br>**Tu Hotel Digital completo (hasta 10 páginas):** Página web profesional con secciones de inicio, habitaciones, servicios, ubicación, galería, contacto y más.<br>**Sistema de Reservas Directo:** Motor de reservas integrado donde tus huéspedes pueden reservar directamente sin intermediarios. 0% de comisión por reserva.<br>**Código QR dinámico:** Para colocar en tu recepción, habitaciones o tarjetas de presentación. Los huéspedes escanean y acceden a todo tu hotel.<br>**Actualizaciones ilimitadas desde tu celular:** Cambia precios, disponibilidad, fotos o descripciones cuando quieras, sin límites.<br>**1 año de dominio + hosting incluidos:** Tu propio dominio (www.tuhotel.com) con alojamiento seguro.<br>**Todo queda a TU nombre:** Propiedad 100% del dominio, sistema y contenido. Cero dependencia.<br>**Posicionamiento Google Básico:** Optimización para búsquedas locales como 'hotel en [tu ciudad]' o 'hostal cerca de [atractivo turístico]'.<br>**Integración WhatsApp:** Reservas directas por WhatsApp integrado.<br><br>Este plan está diseñado para hostales o hoteles pequeños (5-15 habitaciones) sin restaurante, enfocados solo en alojamiento, que quieren recuperar el control de su negocio.",
        benefits: "**Ahorro Brutal en Comisiones:** Booking te cobra 18% por reserva. Con 4-5 reservas directas al mes ya recuperaste tu inversión completa.<br>**Propiedad de Tus Clientes:** Capturas el email y contacto de cada huésped. Ellos son TUYOS, no de Booking.<br>**Fidelización Automática:** Año 1 pagan comisión a la OTA. Año 2 y 3 reservan directo contigo. Cero comisión.<br>**ROI en 45-60 Días:** Con un hotel de ocupación promedio, recuperas tu inversión en 2 meses. El resto del año es ganancia pura.<br>**Reservas Directas 24/7:** Tu sistema trabaja mientras duermes. Los huéspedes pueden reservar cualquier día, a cualquier hora.<br>**Control Total de Precios:** Ajusta tarifas según temporada, eventos o promociones en segundos desde tu celular.<br>**Posicionamiento Local:** Aparecer en Google cuando buscan 'hotel en [tu ciudad]' es oro puro. El 59% busca online antes de reservar.<br>**Inversión Única:** $700 una sola vez. Booking te cobra 18% POR SIEMPRE. Haz las cuentas.<br>**Sin Mensualidades:** Cero costos recurrentes. Pagas una vez y es tuyo para siempre.<br>**Cero Dependencia Tecnológica:** Si decides cambiar de proveedor, te llevas TODO porque es tuyo.<br>**WhatsApp Integrado:** Los huéspedes te contactan directo. Consultas, reservas y seguimiento en un solo lugar.<br>**Soporte Incluido:** Te ayudamos con dudas y cambios durante la implementación.<br>**El Mejor Margen:** Trabajas para ti, no para Booking. Cada reserva directa es 18% más de utilidad en tu bolsillo.",
        category: "Gestión Hotelera y Tecnología Turística",
        subCategory: "Motor de Reservas Hotel / Plan Básico",
        tags: "motor de reservas, hoteles, sin comisiones, booking alternativa, gestión hotelera, Ecuador, hostales, sistema de reservas",
        paymentForm: "Pago único (60/40: 60% inicio, 40% al finalizar)",
        videoUrl: "https://www.youtube.com/watch?v=JDMmFvf8URY",
        servicesIncluded: "Website hotel 10 páginas, Sistema reservas directo 0% comisión, Código QR dinámico, Actualizaciones ilimitadas, Dominio 1 año, Hosting 1 año, Posicionamiento Google básico, Integración WhatsApp, Capacitación personalizada, Soporte técnico"
    },
    {
        sourceId: 7,
        name: "Motor de Reservas Hotel - Plan Élite",
        price: 1800,
        description: "El Plan Élite es la solución completa para hoteles medianos que buscan dominancia en su ciudad y captar el mercado local. Este es el plan más elegido por hoteles que entienden que el futuro es digital. Incluye:<br><br>**Tu Hotel Digital Ampliado (hasta 20 páginas):** Website completo con habitaciones detalladas, servicios, restaurante, eventos, galería extensa, blog de turismo local y más.<br>**Sistema de Reservas Profesional:** Motor de reservas directo sin comisiones, con gestión de disponibilidad en tiempo real.<br>**Código QR dinámico:** Tecnología de actualización continua.<br>**Actualizaciones ilimitadas desde tu celular:** Control total sin restricciones.<br>**2 años de dominio + hosting incluidos:** Protección extendida de tu inversión.<br>**Todo queda a TU nombre:** Propiedad absoluta de tu sistema.<br>**Posicionamiento Google Profesional:** Estrategia SEO con 50+ keywords optimizadas para dominar búsquedas locales como 'mejor hotel [tu ciudad]', 'hotel con piscina [zona]', 'dónde hospedarse [región]'.<br>**15 Artículos de Blog:** Contenido optimizado sobre turismo local, atractivos cercanos y guías de viaje que posicionan tu hotel.<br>**Google My Business Completo:** Configuración y optimización profesional de tu perfil de Google para aparecer en Google Maps.<br>**Posicionamiento en IA (ChatGPT/Claude):** Tu hotel será recomendado cuando viajeros pregunten a la inteligencia artificial dónde hospedarse.<br>**12 Meses de Informes Mensuales:** Reportes detallados de tráfico, reservas, conversiones y ROI.<br><br>Este plan es ideal para hoteles de 10-40 habitaciones que quieren dominar las búsquedas locales y captar huéspedes directos sin pagar comisiones a OTAs.",
        benefits: "**Dominancia Local Absoluta:** Con 50+ keywords optimizadas, tu hotel aparece en TODAS las búsquedas relevantes de tu ciudad.<br>**ROI Proyectado:** 10-15 reservas directas al mes. Eso son $88,200 USD ahorrados en comisiones al año.<br>**Posicionamiento en IA:** Cuando alguien pregunta a ChatGPT 'mejores hoteles en [tu ciudad]', TÚ apareces. Eso es el futuro.<br>**Blog de Contenido:** 15 artículos sobre turismo local atraen tráfico orgánico constante. Es marketing que trabaja 24/7.<br>**Google My Business Premium:** Aparecer en Google Maps con fotos, reseñas y disponibilidad es donde se ganan las reservas locales.<br>**Capturas al Turista Local:** El ecuatoriano que busca 'hotel en [tu ciudad]' para fin de semana ahora te encuentra PRIMERO.<br>**12 Meses de Análisis:** Informes mensuales te muestran exactamente cuánto estás ganando, qué funciona y cómo mejorar.<br>**2 Años Sin Preocupaciones:** Dominio y hosting cubiertos por 24 meses. Ahorro significativo.<br>**Fidelización Comprobada:** Año 1 pagan comisión a Booking. Años 2, 3, 4, 5... reservan directo contigo. Multiplica eso por 100 huéspedes.<br>**Sin Comisiones Vitalicias:** Mientras otros hoteles pagan 18% por siempre, tú cobras 100% de cada reserva.<br>**Propiedad Total:** El sistema es tuyo. Si en 5 años decides cambiar, te llevas todo.<br>**Soporte Extendido:** Atención prioritaria durante 12 meses completos.<br>**Ventaja Competitiva:** Mientras tu competencia sigue dependiendo de Booking, tú dominas Google y la IA.<br>**Diversificación de Ingresos:** Con el blog atraes eventos corporativos, grupos turísticos y retiros que buscan hoteles con buena presencia digital.",
        category: "Gestión Hotelera y Tecnología Turística",
        subCategory: "Motor de Reservas Hotel / Plan Profesional",
        tags: "motor de reservas, hoteles medianos, SEO hotelero, marketing digital, sin comisiones, dominancia local, Ecuador, turismo",
        paymentForm: "Pago único (60/40: 60% inicio, 40% al finalizar)",
        videoUrl: "https://www.youtube.com/watch?v=JDMmFvf8URY",
        servicesIncluded: "Website hotel 20 páginas, Sistema reservas directo 0% comisión, Código QR dinámico, Actualizaciones ilimitadas, Dominio 2 años, Hosting 2 años, SEO profesional 50+ keywords, 15 artículos blog, Google My Business completo, Posicionamiento IA, 12 informes mensuales, Capacitación personalizada, Soporte prioritario 12 meses"
    },
    {
        sourceId: 8,
        name: "Motor de Reservas Hotel - Plan Imperio",
        price: 2800,
        description: "El Plan Imperio es la solución definitiva para hoteles boutique y cadenas hoteleras que buscan ser LA REFERENCIA en su región y posicionarse a nivel nacional e internacional. Incluye:<br><br>**Tu Imperio Digital (hasta 40 páginas):** Website completo con secciones de habitaciones premium, suites, servicios, restaurante, spa, eventos corporativos, bodas, galería extensa, blog de turismo, guías locales, historia del hotel y mucho más.<br>**Sistema de Reservas Empresarial:** Motor de reservas profesional con gestión multihabitación, promociones automáticas y reportes avanzados.<br>**Código QR dinámico:** Tecnología premium de actualización continua.<br>**Actualizaciones ilimitadas desde tu celular:** Control absoluto sin límites.<br>**2 años de dominio + hosting incluidos:** Infraestructura premium protegida.<br>**Todo queda a TU nombre:** Propiedad vitalicia de tu imperio digital.<br>**Posicionamiento Google Premium:** Estrategia SEO agresiva con 100+ keywords optimizadas para dominar búsquedas locales, regionales y nacionales.<br>**30 Artículos de Blog:** Contenido extenso sobre turismo, guías de viaje, gastronomía local, eventos regionales que posicionan tu hotel como autoridad.<br>**Google My Business Premium:** Optimización avanzada con fotos profesionales, tours virtuales y gestión de reseñas.<br>**Posicionamiento en IA (ChatGPT/Claude):** Tu hotel será recomendado cuando viajeros pregunten a la inteligencia artificial dónde hospedarse.<br>**12 Meses de Informes Mensuales de Rendimiento (BONUS $1,800):** Análisis profundo de tráfico, conversiones, ROI y recomendaciones estratégicas personalizadas.<br><br>Este plan es para hoteles boutique o cadenas (20-80 habitaciones) que quieren ser LA REFERENCIA y ven 5 años adelante.",
        benefits: "**Dominancia Regional Total:** Con 100+ keywords optimizadas, dominas no solo tu ciudad sino toda la región. Turistas de otras provincias te encuentran primero.<br>**ROI Proyectado Millonario:** 20-30 reservas directas al mes son $176,400 USD ahorrados en comisiones AL AÑO. Multiplica eso por 5 años.<br>**Posicionamiento IA Premium:** ChatGPT y Claude te recomiendan PRIMERO cuando preguntan por hoteles en tu zona. Eso es futuro puro.<br>**30 Artículos de Autoridad:** No solo contenido, sino guías completas sobre turismo local que te posicionan como LA autoridad regional.<br>**Google My Business Premium:** Tours virtuales, fotos profesionales y gestión avanzada que te pone arriba en Google Maps.<br>**Sistema Empresarial:** Gestión multihabitación, promociones automáticas y reportes que una cadena internacional usaría.<br>**40 Páginas de Contenido:** Cuentas tu historia completa. Historia del hotel, equipo, valores, servicios premium, experiencias únicas.<br>**Captura Mercado Corporativo:** Con presencia premium atraes eventos corporativos, retiros empresariales, conferencias y bodas.<br>**Captura Mercado Turístico Nacional e Internacional:** El 70% de viajeros busca online. Con este nivel de presencia, los capturas a TODOS.<br>**Bonus $1,800 en Informes:** 12 meses de análisis profesional incluidos. Sabes EXACTAMENTE qué funciona y cómo escalar.<br>**2 Años Sin Preocupaciones:** Infraestructura premium protegida por 24 meses completos.<br>**Fidelización Exponencial:** Cada huésped que capturas año 1 se convierte en cliente directo años 2, 3, 4, 5, 10. Sin comisiones para siempre.<br>**Propiedad Perpetua:** Todo es tuyo para siempre. En 10 años seguirás siendo dueño del sistema más valioso de tu hotel.<br>**Ventaja Competitiva Brutal:** Mientras hoteles vecinos pagan comisiones eternamente, tú construyes un activo que vale millones.<br>**Diversificación Premium:** Eventos, bodas, retiros, grupos corporativos, turismo de experiencias. Tu presencia digital abre TODOS los mercados.<br>**Soporte VIP Vitalicio:** Atención personalizada prioritaria durante los 12 meses de informes y soporte extendido posterior.<br>**Visión 5 Años:** Esta inversión se paga sola en 3-4 meses. Los próximos 4 años y 8 meses son ganancia directa al bolsillo.",
        category: "Gestión Hotelera y Tecnología Turística",
        subCategory: "Motor de Reservas Hotel / Plan Premium",
        tags: "motor de reservas premium, hoteles boutique, cadenas hoteleras, SEO nacional, marketing hotelero, sin comisiones, Ecuador, turismo",
        paymentForm: "Pago único (60/40: 60% inicio, 40% al finalizar)",
        videoUrl: "https://www.youtube.com/watch?v=JDMmFvf8URY",
        servicesIncluded: "Website hotel 40 páginas, Sistema reservas empresarial 0% comisión, Código QR dinámico, Actualizaciones ilimitadas, Dominio 2 años, Hosting 2 años, SEO premium 100+ keywords, 30 artículos blog, Google My Business premium, Posicionamiento IA prioritario, 12 informes mensuales BONUS ($1,800), Capacitación personalizada, Soporte VIP 12 meses"
    },
];

async function seed() {
    console.log("Seeding products...");

    for (const product of SEED_DATA) {
        // Check if exists by name to avoid duplicates
        const existing = await db.query.products.findFirst({
            where: eq(products.name, product.name),
        });

        if (!existing) {
            await db.insert(products).values(product);
            console.log(`Created: ${product.name}`);
        } else {
            console.log(`Skipped (already exists): ${product.name}`);
        }
    }

    console.log("Seeding complete!");
    process.exit(0);
}

seed().catch((err) => {
    console.error("Seeding failed", err);
    process.exit(1);
});
